### ISSUE TITLE
Label super CAPFs

### ISSUE THREAD

**Issue by jdtsmith** [minad/cape#10]
If cape-super-capf could take an optional _tag_, per capf:

```elisp
(setq-local completion-at-point-functions
            (list (cape-super-capf #'my-fancy-mode-capf
				   '(cape-dabbrev-capf "dab")
				   '(cape-dict-capf    "dict")
				   '(cape-keyword-capf "kw")
				   '(cape-file-capf    "file"))))
```

you could _label_ the results by the capf from which they came, by wrapping the annotation function to append the (styled) tag, if any.

**Comment by jdtsmith** [comment]
Or, instead of user-config'd, could have the capf's themselves specify such a tag using an extra property, or use their category (possibly too long).   In either case, overridability would be nice though.

**Comment by minad** [comment]
What is the meaning of this tag? Should it be used for annotations? 

Note that you can already do this, which is a bit verbose.

~~~ elisp
(setq completion-at-point-functions (list (cape-super-capf
                                           (cape-capf-with-properties #'cape-dabbrev-capf :annotation-function (lambda (_) " Y"))
                                           (cape-capf-with-properties #'cape-dict-capf :annotation-function (lambda (_) " X")))))
~~~

But if you do this often you can also write a small helper `(cape-with-annotation #'cape-dict-capf "X")`. I assume this answers the question?
