### ISSUE TITLE
Error during compilation on emacs 28

### ISSUE THREAD

**Issue by Vietoonet** [minad/cape#16]
Compiling file /home/viet/.emacs.d/elpa-28.0/cape-20211209.2349/cape.el at Fri Dec 10 08:44:24 2021
Entering directory ‘/home/viet/.emacs.d/elpa-28.0/cape-20211209.2349/’
cape.el:672:1: Error: Attempt to delete minibuffer or sole ordinary window

Compiling internal form(s) at Fri Dec 10 08:48:28 2021

This error raises an error in my init.el when starting Emacs.
For info, my init.el : 
(require 'cape)
   (with-eval-after-load 'cape
     (setq cape-dabbrev-min-length 2)
     (dolist (backend '( cape-keyword cape-file cape-dabbrev))
       (add-to-list 'completion-at-point-functions backend)))

**Comment by minad** [comment]
Please check if https://github.com/minad/cape/commit/1e73d032e45381d0d3b9baca47ca1431f0bbbec1 fixes the issue for you.

**Comment by Vietoonet** [comment]
Seems to work after commit 1e73d03 ! Thx!
