### ISSUE TITLE
First candidate is not selected in `cape-file` when completing

### ISSUE THREAD

**Issue by liebkne** [minad/cape#20]
Compared to other `cape-*` functions, `cape-file` does not select the first candidate when the frame shows up. Is it by design? Thanks.

<img width="703" alt="Screen Shot 2022-01-06 at 6 22 33 PM" src="https://user-images.githubusercontent.com/5475262/148368988-e892b2af-d87b-4655-ac59-73b53c58d4da.png">
<img width="703" alt="Screen Shot 2022-01-06 at 6 26 51 PM" src="https://user-images.githubusercontent.com/5475262/148368996-d21a7187-c26b-4efc-bd27-57dd86b366e2.png">

Config:

```el
(setq user-init-file (or load-file-name (buffer-file-name)))
(setq user-emacs-directory (file-name-directory user-init-file))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

(require 'package)
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(setq package-user-dir (expand-file-name "elpa/" user-emacs-directory))
(package-initialize)

;; Install use-package that we require for managing all other dependencies
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(package-install 'corfu)
(package-install 'multiple-cursors)
(package-install 'cape)

(setq corfu-auto t)
(corfu-global-mode)

(add-to-list 'completion-at-point-functions #'cape-file)
```

**Comment by minad** [comment]
This is by design since the input is a valid file path. Otherwise you wouldn't be able to input directory paths.

**Comment by liebkne** [comment]
The `company` way seems better since it's has the advantage of `TAB` quickly to access deep nested files to minimize the `C-n`s. To insert a directory, aren't both libraries require a `C-g`?


<img width="387" alt="Screen Shot 2022-01-06 at 8 42 14 PM" src="https://user-images.githubusercontent.com/5475262/148384723-dfe64063-024a-41dc-aaa7-6ab0b030eaea.png">

<img width="387" alt="Screen Shot 2022-01-06 at 8 42 43 PM" src="https://user-images.githubusercontent.com/5475262/148384729-d7543171-44b3-419a-9306-e2ca3382dcf0.png">

**Comment by minad** [comment]
> The company way seems better since it's has the advantage of TAB quickly to access deep nested files to minimize the C-ns. To insert a directory, aren't both libraries require a C-g?

I disagree. Corfu uses the underlying Emacs file completion table as is. There you don't complete full paths but the files step by step.

Anyways if you prefer the Company way you can either use Company or use the Company backend with Corfu/Cape.

~~~ elisp
(fset #'cape-path (cape-company-to-capf #'company-files))
(add-hook 'completion-at-point-functions #'cape-path)
~~~

**Comment by liebkne** [comment]
That works! Thanks!
