### ISSUE TITLE
Error in `cape--company-call`: <cape--done> is undefined

### ISSUE THREAD

**Issue by galeo** [minad/cape#23]
I am trying to use [`company-jedi`](https://github.com/emacsorphanage/company-jedi) (fetch completion candidates asynchronously) with `cape-company-to-capf`. It reports an error: `<cape--done> is undefined`.

After some digging, it turns out that the `cape--done` event added in the future callback are not removed from `unread-command-events`. The value of `unread-command-events` actually is `((t . cape--done))`. I don't know why its value changed from `(cape--done)` to `((t . cape--done))`. 

https://github.com/minad/cape/blob/9db78299616bab3c601ace2bcab205c9fbff8dd0/cape.el#L895-L896

Simply changing the code `(delq 'cape--done unread-command-events)` to `(delete (cons t 'cape--done) unread-command-events)` can avoid this error. I'm just not clear why the value of `unread-command-events` changed.

Thanks.

**Comment by minad** [comment]
This is an Emacs bug. I think Company has observed the same issue.

**Comment by minad** [comment]
> Simply changing the code (delq 'cape--done unread-command-events) to (delete (cons t 'cape--done) unread-command-events) can avoid this error.

We should keep the delq and add the delete on top. I think both cape--done and (t.cape--done) can occur.

**Comment by galeo** [comment]
> We should keep the delq and add the delete on top. I think both cape--done and (t.cape--done) can occur.

👍

**Comment by galeo** [comment]
After 45fe322, it still reports the `<cape--done> is undefined` error, although `unread-command-events` is `nil`. I don't have enough time to check further now. I feel that the `cape--done` event added in the asynchronous callback was not removed in time before handling `unread-command-events`. Can we just ignore the interrupt handling when typing input? It may be similar to `company--force-sync` in company.

Thanks.

**Comment by minad** [comment]
> Can we just ignore the interrupt handling when typing input? It may be similar to company--force-sync in company.

No. The interrupt handling should work as is. See company--fetch-candidates. Are we doing something differently?

**Comment by galeo** [comment]
I've tried 3b019d5, the problem is still unresolved.

**Comment by alternateved** [comment]
Hello, I think I might suffer from the similar issue. I try to use Corfu with `psc-ide` like so:
```lisp
(setq-local completion-at-point-functions
      (list (cape-company-to-capf #'company-psc-ide-backend)))
```

The result of that is that something (most likely completion but there is no child frame popup) hangs every now and then - I have to manually exit process by `C-g`. Then in the minibuffer I see the message:
```
<cape--done> is undefined
```

If there is anything else that I could provide that would be helpful, please let me know.
