### ISSUE TITLE
Integrate with emmet-mode

### ISSUE THREAD

**Issue by vmsp** [minad/cape#27]
Emmet allows you to easily expand a snippet to valid markup. E.g.

```
main.class1.class2|
```

becomes

```
<main class="class1 class">
  |
</main>
```

https://github.com/smihica/emmet-mode

**Comment by minad** [comment]
Emmet-mode looks nice. Unfortunately it seems unmaintained. 

Integrations with third party packages are out of scope for Cape. But one could add a Capf in the style of Cape to emmet-mode. See also my [Tempel package](/minad/tempel) which provides the Capfs `tempel-expand` and `tempel-complete`. One could add an `emmet-expand` Capf in a similar style to emmet-mode. Please open an issue there!
