### ISSUE TITLE
Add a version of cape-line that collects candidates from all buffers with the same major mode

### ISSUE THREAD

**Issue by daanturo** [minad/cape#36]
I think we can implement this by writing another version of `cape--line-list` that operate on relevant buffers, or extend the current one.
```lisp
(defun my-cape--line-list (&optional all)
  "Return all lines from buffer.
With non-nil ALL, return all lines from buffers with the same
major mode as the current one."
  (let ((ht (make-hash-table :test #'equal))
        end lines
        (mode major-mode))
    (dolist (buf (if all
                     (buffer-list)
                   (list (current-buffer))))
      (with-current-buffer buf
        (when (equal mode major-mode)
          (let ((beg (point-min))
                (max (point-max))
                (pt (point)))
            (save-excursion
              (while (< beg max)
                (goto-char beg)
                (setq end (line-end-position))
                (unless (<= beg pt end)
                  (let ((line (buffer-substring-no-properties beg end)))
                    (unless (or (string-blank-p line) (gethash line ht))
                      (puthash line t ht)
                      (push line lines))))
                (setq beg (1+ end))))))))
    (nreverse lines)))
```

**Comment by minad** [comment]
Sounds good. I think the following approach would be good:

- We generalize `cape-line`
- Generalize `cape--line-list` to retrieve the lines from a list of buffers (or a single buffer) returned from a configurable `cape-line-buffer-function`.
- `cape-line-buffer-function` can then be set to `current-buffer` if you want only this buffer, `buffer-list` if you want all buffers, and `cape-major-mode-buffers` which returns a list of only the buffers with the same major mode.

I am happy to accept a patch which implements this. See https://github.com/minad/cape/#contributions.

**Comment by daanturo** [comment]
Thank you.
