### ISSUE TITLE
Multiple backend completion problems

### ISSUE THREAD

**Issue by e190** [minad/cape#39]
First I use cape,corfu in c file.

If cape-dabbrev and cape-keyword are both on the back end of autocomplete, then the completion candidates will not be all, either with the result of the keyword or the result of dabbrev.

`completion-at-point-functions` is:
![图片](https://user-images.githubusercontent.com/39932163/168805008-e70c9e92-3782-41f5-95bb-3824f50f6f2c.png)

Result of auto-completion:
![图片](https://user-images.githubusercontent.com/39932163/168805213-efb6ff62-a0f1-4f16-8d81-b9ae7785d1ef.png)

Result of cape-dabbrev:
![图片](https://user-images.githubusercontent.com/39932163/168805337-a28f2f9c-1c0b-443a-a90f-527dd9bc4537.png)

I want the cape-dabbrev and cape-keyword results to appear in both autocomplete.

I also found a problem with cape-Dabbrev's autocomplete, I typed the same character, sometimes the result was different, for example, the results of the following two images appeared in the same window.

![图片](https://user-images.githubusercontent.com/39932163/168805849-f55b60c2-5241-42de-8366-3e844a88e4d6.png)
![图片](https://user-images.githubusercontent.com/39932163/168805957-a758ad70-44d6-48b9-bc2f-dc3da37b450b.png)

**Comment by minad** [comment]
1. The backends will be tried one after the other. Therefore the results don't appear together. See also cape-super-capf.
2. The second issue may be a problem with dabbrev. Can you please create a minimal recipe for me to reproduce this if there is indeed an issue.
