### ISSUE TITLE
cape-company-to-capf's returned CAPF may not give sorted candidates through corfu

### ISSUE THREAD

**Issue by daanturo** [minad/cape#44]
Specifically I use `elpy-company-backend` via `cape-company-to-capf`.

![image](https://user-images.githubusercontent.com/32123754/172005569-619c8140-8192-4ccd-ae1d-f657a9a4e454.png)

`cape-company-to-capf` disables sorting when the backend reports itself as sorted (alphabetically in this case?):
```elisp
       :sort (not (cape--company-call backend 'sorted))
```

Disabling the above `:sort` key make candidates appear sorted by length normally like other CAPFs through Corfu.

Can you expose a flag at CAPF creation time that can force sorting?

**Comment by minad** [comment]
You can use the cape-capf-properties Transformer.

**Comment by daanturo** [comment]
> use the cape-capf-properties transformer

Can you give an example how to use that function correctly? There hasn't been one in the README yet.
I tried
```lisp
(defalias #'my-elpy-company-capf
  (cape-capf-properties (cape-company-to-capf 'elpy-company-backend)
                        :sort t))
```

Still not sorted. I logged `cape--table-with-properties` and saw `sort` at `nil`.

**Comment by minad** [comment]
Hmm, this should work in principle. Did you check the backend sort function in Corfu?

**Comment by daanturo** [comment]
![image](https://user-images.githubusercontent.com/32123754/172017520-fe007d25-80e6-4247-855e-e571c0b3ab75.png)

`corfu--sort-function` always return `corfu-sort-length-alpha`.

As I observed, the condition to return TABLE as-is is most of the time as truthy/falsy as SORT.
So it either returns TABLE without sorting (SORT as `t`) or modified TABLE with SORT as nil.

**Comment by daanturo** [comment]
Looks like at `cape-wrap-properties`:

```elisp
;;;###autoload
(defun cape-wrap-properties (capf &rest properties)
  "Call CAPF and add additional completion PROPERTIES.
Completion properties include for example :exclusive, :annotation-function and
the various :company-* extensions. Furthermore a boolean :sort flag and a
completion :category symbol can be specified."
  (pcase (funcall capf)
    (`(,beg ,end ,table . ,plist)
     (my-message "708 cape.el"
                 ;; This expr is always `t'
                 (or (not table)
                     (and (not (plist-get plist :category))
                           properties)))
     `(,beg ,end
            ,(apply #'cape--table-with-properties table properties)
            ,@properties ,@plist))))
```

The arguments passed to `cape--table-with-properties` will always satisfy the `if` condition so TABLE is returned unmodified (non-nil TABLE, no category, :SORT t).

**Comment by minad** [comment]
> corfu--sort-function always return corfu-sort-length-alpha.

Well, that's good then. This means that the sort function of the backend is ignored as you wanted? You can also chose a different sort function, e.g. the one from corfu-history.

**Comment by daanturo** [comment]
> Well, that's good then. This means that the sort function of the backend is ignored as you wanted?

No, I meant sorting by length isn't applied at that time despite the correct returned value of `corfu--sort-function`.
I think the problem lies at `cape--table-with-properties`'s `(and (not category) sort)` as commented above, `cape-capf-properties` indeed works after removing that condition.

**Comment by minad** [comment]
Btw, you can also use corfu-sort-override-function in case you disagree with the sort function specified by the backend.

**Comment by daanturo** [comment]
!! Without modifying `cape`'s source or touching `corfu-sort-override-function`, this can worked around by enforcing `:category` using `cape-capf-properties` so that `(and (not category) sort)` is always nil.

Still not understand, though.
