### ISSUE TITLE
how can I add a cape-super-capf backend to completion-at-point-functions?

### ISSUE THREAD

**Issue by haoisli9** [minad/cape#47]
I want add a cape-super-capf backend to completion-at-point-functions, but still keep other backend in  completion-at-point-functions list. I write this as:  
 (add-to-list 'completion-at-point-functions
              #'(cape-super-capf #'cape-dabbrev #'tabnine-completion-at-point))
but seems not work. 

how can I get this?

Thanks.

**Comment by minad** [comment]
Duplicate #46.
