### ISSUE TITLE
cape-dabbrev-project

### ISSUE THREAD

**Issue by jdtsmith** [minad/cape#48]
Not sure if you'd want a wishlist issue for CAPE, but here's an idea:

- `cape-dabbrev-project`: project-aware dabbrev that limits itself to files in this project, or, if no project is detected, falls back on files in the same major-mode.

**Comment by minad** [comment]
Not needed, you can adjust cape-dabbrev-check-other-buffers and the buffer select functions.

I may reconsider this when we would implement a better dabbrev from scratch. But currently cape-dabbrev just relies on dabbrev.el.
