### ISSUE TITLE
cape-dabbrev doesn't respect "dabbrev-case-replace"?

### ISSUE THREAD

**Issue by zhenhua-wang** [minad/cape#51]
Suppose we have "EmaCs" in our buffer and we want to expand "em" to it. When `dabbrev-case-replace` set to t, `dabbrev-completion` would expand "em" to "emacs" which is the expected behavior , but `cape-dabbrev` expands "em" to "EmaCs". 

I didn't find a setting similar to `dabbrev-case-replace` in cape. Did I miss something?

**Comment by minad** [comment]
Cape doesn't support this currently. PR welcome.
