### ISSUE TITLE
Does `cape-dabbrev-min-length` work as expected? It seems to drop some candidates?

### ISSUE THREAD

**Issue by Dima-369** [minad/cape#55]
Start with this:

![image](https://user-images.githubusercontent.com/15002298/181688906-d06741d1-dc17-4064-8ac8-bc541ad22f6b.png)

Here `cape-dabbrev` correctly picks up `longwordishere` and suggests it.

Now, I finish typing the word and backspace twice. Next I enter `r` and I assume that the same word will be suggested again, but alas that is not the case? 

![image](https://user-images.githubusercontent.com/15002298/181688959-92f9c049-9bb8-46dc-bd2a-d80ad094e688.png)

It is only when I backspace more that `longwordishere` is suggested again when I type in a character again to trigger corfu. I believe the amount of backspacing is directly correlated to the setting of `cape-dabbrev-min-length`. 

![image](https://user-images.githubusercontent.com/15002298/181689111-feffebc5-643f-4903-91b2-26e873f8abc4.png)

---

As a workaround I have set `cape-dabbrev-min-length` to 0 for now.

Is this intended or a bug? I find it a bit weird that the candidates are 'lost'.

**Comment by minad** [comment]
Works as intended. See cape--dabbrev-list.
