### ISSUE TITLE
cape-symbol suggests (unwanted) symbol description strings

### ISSUE THREAD

**Issue by sonofjon** [minad/cape#59]
Hi,

I find cape-symbol quite useful, but the completion list is often littered with symbol "descripton strings" when I write in text buffers, which I find not so useful, see image below. Is there a way to disable these desctiptions while maintaing completion of the symbols themselves?

![Screen Shot 2022-08-24 at 10 40 05](https://user-images.githubusercontent.com/7573435/186373473-7ce32e49-afa2-478c-91d4-af3c6be130f8.png)

**Comment by minad** [comment]
That's odd. cape-symbol uses the Elisp symbols. If for some reason weird strings are internalized, these will be offered for completion. It is an issue of your setup.
