### ISSUE TITLE
 ispell-change-dictionary seems to have no effect on cape-ispell

### ISSUE THREAD

**Issue by vincent-picaud** [minad/cape#70]
Changing language thanks to ispell-change-dictionary has no effect on cape-ispell which still presents English words even if I have chosen the "francais" (French) language.

You can test it with "maison" which is a French word (meaning "house") but not an English one.

Thanks !

**Comment by minad** [comment]
Indeed, I could reproduce this. Unfortunately I don't have an idea why this happens. This needs some digging into ispell.el.

**Comment by minad** [comment]
In order to change the word list you have to change the variable `ispell-complete-word-dict` or `ispell-alternate-dictionary`. For some reason this variable is not modified by `ispell-change-dictionary`.
