### ISSUE TITLE
Company wrapper when used for thing starting with non-letter is sometimes inconsistent with original company command

### ISSUE THREAD

**Issue by BlankSpruce** [minad/cape#72]
In my setup I have installed the following packages:
- `cape`
- `company`
- `embark` (to demonstrate list of the candidates)
- `yasnippet`
- `yasnippet-snippets`

The last one provides a couple of templates for org-mode that start with `<`:
![image](https://user-images.githubusercontent.com/32396809/214358191-6a26b9b3-befd-46d4-a15e-15d15714f01f.png)
In particular I'm interested in this template: https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/org-mode/src which has `<src` key.

I use `cape-company-to-capf` to get relevant yasnippet templates. For the purpose of this report I invoke it with `M-: (call-interactively (cape-interactive-capf (cape-company-to-capf #'company-yasnippet)))`.
Given the initial state of the buffer: 
![image](https://user-images.githubusercontent.com/32396809/214359124-c4141559-dc4b-409b-9e16-8de259cb99fe.png)

I get a long list of candidates and among them is `<src` I'm looking for:
![image](https://user-images.githubusercontent.com/32396809/214358556-8d793970-6ffd-489a-81e9-bb7c2e715a8b.png)
![image](https://user-images.githubusercontent.com/32396809/214363955-14b6fde9-9fee-4326-8be5-b79160512c05.png)

When my buffer is in this state:
![image](https://user-images.githubusercontent.com/32396809/214359450-eb3df208-5d8e-46dc-85e4-b38a81b1402f.png)

it immediately expands to:
![image](https://user-images.githubusercontent.com/32396809/214359748-10957212-61b3-4e38-a99b-d52c31227892.png)
which is associated to this snippet instead https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/org-mode/setup (key `set`). This result is "kind of correct" since it's at least consistent with how `company` behaves here (example further in this report).

With buffer state:
![image](https://user-images.githubusercontent.com/32396809/214360227-646d4b88-f1d3-4a09-ba82-724b46688d06.png)

no candidates are offered but a cryptic message is printed instead:
![image](https://user-images.githubusercontent.com/32396809/214361110-d07af666-1f8f-474d-bf8d-ee3836d5642d.png)

And with this buffer state:
![image](https://user-images.githubusercontent.com/32396809/214360491-2d1d03cf-0a2f-41fb-b170-300031618146.png)

I don't get neither candidates nor it expands (because there should be the only candidate that matches `<src`) with similar cryptic message:
![image](https://user-images.githubusercontent.com/32396809/214360979-a0a2401a-198c-46e3-9896-81b3787e1065.png)

Comparing that situation to invoking `M-x company-yasnippet` these are the results:
- initial `<`:
![image](https://user-images.githubusercontent.com/32396809/214361487-8a762efc-407c-436e-95e1-09c634945261.png)

- initial `<s`:
![image](https://user-images.githubusercontent.com/32396809/214361543-05148a61-4bd3-4990-a06b-36480a6b631b.png)
Note: `company` makes the same mistake here by considering `s` as a start instead of `<s` but for the sake of this report let's just focus on inconsistency between `cape` wrapper and `company`.

- initial `<sr`:
![image](https://user-images.githubusercontent.com/32396809/214361596-85ba5f4a-9052-4ccb-b00e-1f540ab8f898.png)

- initial `<src`:
![image](https://user-images.githubusercontent.com/32396809/214361651-72997462-305c-4384-a2b3-32ceb90be7fb.png)

There's not much to do with unexpected suggestion at input `<s` because that's how company behaves here but at least the wrapper should offer the same candidates as company does. As far as I've experienced that it behaves like that with at least two letter inputs starting with non-letter.

**Comment by minad** [comment]
Thanks for the report. Unfortunately I need more information to act.

Can you try this with Corfu and provide me with a minimal self-contained example which I can actually test? I haven't used the Company Capf converter much, but in my basic tests of some common Company backends it went well. It exceeds my bandwidth to support and test additional packages like Yasnippet. Some parts of Cape are tricky, e.g., `cape-company-to-capf` and `cape-super-capf`. I am not sure, but I think some people already use Corfu+cape-company-to-capf+Yasnippet successfully.

If you are interested it would be great if you dig deeper and figure out the reason for the deviation you observed. Ideally you could provide an example where `cape-company-to-capf` does the wrong thing for a Company backend, which does not depend on an additional package like Yasnippet?

(Maybe someone has written a `yasnippet-capf` in the meantime, which you could try. If not, you could also use my Tempel package, but that's maybe asking too much if you are already heavily invested in Yasnippet.)
