### ISSUE TITLE
Cape with lsp crash

### ISSUE THREAD

**Issue by deb75** [minad/cape#76]
Hi,

I use `lsp-java` / emacs 29.0.60 / mingw64 / windows 10 (all upgraded to the latest)

When I start completion at point, it runs well but as soon as I hit return, once I found the right completion,
emacs crashes with an "emacs_backtrace.txt" file. It is completely reproducible, happens any time I am doing this.

It only happens with `lsp-java`, completion works fine with `lsp-pyright`

I do not know whether it is a bug from `lsp` or `cape`

Does someone experiment the same issue ?

Regards

**Comment by minad** [comment]
This sounds like an Emacs bug which you should report via report-emacs-bug.
