### ISSUE TITLE
No completion from eglot after applying `cape-capf-buster`

### ISSUE THREAD

**Issue by rrudakov** [minad/cape#79]
Steps to reproduce:
- start emacs using `emacs -Q`
- apply the following configuration:
```emacs-lisp
(package-initialize)

(require 'eglot)
(require 'corfu)
(require 'cape)
(setopt corfu-auto t)
(global-corfu-mode)
(advice-add 'eglot-completion-at-point :around #'cape-capf-buster)
```
- open any file which can be managed by eglot
- type a few characters to trigger auto completion
Expected result:
- corfu popup with completion candidates is visible
Actual result:
- no corfu completion popup

Emacs version:
`GNU Emacs 29.0.60 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3 (Build 22E252)) of 2023-03-31`

Before adding advice I can see completion candidates.

**Comment by minad** [comment]
The correct advice is this one:

~~~ elisp
(advice-add #'elisp-completion-at-point :around #'cape-wrap-buster)
~~~

**Comment by rrudakov** [comment]
Yes, it works. Thank you!
