### ISSUE TITLE
Question about cape-tex

### ISSUE THREAD

**Issue by deb75** [minad/cape#80]
When I write a backslash `\` and then hits `C-c q x` (configured to call `cape-tex` for me), I am offered many latex symbols.

However, what I finally get is an UTF-8 symbol, whereas what I would prefer is the latex command, e.g. `\leftarrow`, ...

Is it possible to achieve this ? Perhaps with a cape transformation ?

Regards

**Comment by minad** [comment]
The point of cape-tex is to write Unicode symbols, not tex names. However you could modify cape--tex-properties and remove the :exit-function.

**Comment by deb75** [comment]
Thanks,

I tried : 
```
  (plist-put cape--tex-properties :exit-function nil)
```
either inside or outside (after) `(use-package ...)`, but it did not find the variable `cape--tex-properties`.

Indeed, it seems not known until first call to `cape-tex`. How can I proceed ?

Regards
