### ISSUE TITLE
cape-dict-grep: returns dict file name when multiple dictionaries

### ISSUE THREAD

**Issue by intrigeri** [minad/cape#82]
Hi,

On 0.14, with the default `cape-dict-grep t`, if I set `cape-dict-file` to a list of dictionaries, the completion results are prefixed with the path to the dictionary, followed by a semi-colon: `DICT:WORD`.

I can workaround this by setting `cape-dict-grep` to `nil`. But I suppose a better fix would be to pass `--no-filename` to `grep`.

Thanks for your work!

**Comment by minad** [comment]
Thanks for your report. Please check if the issue is fixed.

**Comment by intrigeri** [comment]
> Please check if the issue is fixed.

As of 06996d5bcdbb6b87b7ccbc4e612851bb8c38a6c4, the problem is fixed:
I don't need the workaround anymore.

Thank you :)
